Repository samueleffiongjacob/Techathon-Group-2-Team-4, pull requests merged in 2022-08, with the labels that each got.

#6 CREATED A BOILER PLATE
  Frontend/.gitignore
  Frontend/index.html
  Frontend/package.json
  Frontend/postcss.config.cjs
  Frontend/src/App.css
  Frontend/src/App.jsx
  Frontend/src/index.css
  Frontend/src/main.jsx
  Frontend/tailwind.config.cjs
  Frontend/vite.config.js
  Frontend/yarn.lock
Labels: documentation

#14 blessingkeyz branch created
  Frontend/index.html
  Frontend/package.json
  Frontend/src/App.jsx
  Frontend/yarn.lock
Labels: enhancement

#20 AUTHROUTE
  server/package.json
  server/server.js
  server/src/controllers/auth.controller.js
  server/src/middleware/auth.middleware.js
  server/src/middleware/error.middleware.js
  server/src/models/admin.model.js
  server/src/models/users.model.js
  server/src/routes/auth.routes.js
  server/src/utils/error.js
  server/src/utils/index.js
Labels: question
